apiVersion: v1
name: techtrends-deployment
description: Install techtrends deployment manifests
keywords:
- techtrends 
version: 1.0.0
maintainers:
- name: alimhabib 
  email: ali.m.habib@hotmail.com
