##Following the officail documentian of Docker https://docs.docker.com/ci-cd/github-actions/
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: move to the techtrends project folder 
        run: cd .\project\techtrends
      -
        name: ls the files 
        run: ls
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/techtrends:latest
## Optimizing the workflow
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/techtrends:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/techtrends:buildcache,mode=max
